services:
  test-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - '5433:5432'
    volumes:
      - test-pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: test
    depends_on:
      - test-db
    network_mode: host
    environment:
      DB_HOST: 127.0.0.1
      DB_PORT: 5433
      DB_DB: test
      DB_USERNAME: test
      DB_PASSWORD: test
      NODE_ENV: test
    ports:
      - '4000:4000'

volumes:
  test-pgdata:
